# Generated by Django 3.2.7 on 2021-09-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='monedaNumero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
