# Generated by Django 3.2.7 on 2021-09-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moneda_monedanumero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
