# Generated by Django 3.2.7 on 2021-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_moneda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='monedaNumero',
            field=models.IntegerField(verbose_name='# Moneda en la coleccion'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
